catalog:
  '@unocss/eslint-plugin': ^66.6.0
  eslint: ^9.39.2
  eslint-plugin-svelte: ^3.14.0
  typescript-eslint: ^8.53.1
  '@eslint/js': ^9.39.2
  '@stylistic/eslint-plugin': ^5.7.1
  eslint-config-flat-gitignore: ^2.1.0
  eslint-flat-config-utils: ^2.1.4
  eslint-plugin-perfectionist: ^5.4.0
  eslint-plugin-regexp: ^3.0.0
  eslint-plugin-unicorn: ^62.0.0
  globals: ^17.1.0
  '@types/node': ^25.0.10
  tsdown: ^0.20.1
  typescript: ^5.9.3
  eslint-plugin-better-tailwindcss: ^4.0.1
