catalog:
  "@unocss/eslint-plugin": ^66.5.1
  eslint: ^9.35.0
  eslint-plugin-svelte: ^3.12.3
  typescript-eslint: ^8.43.0
  "@eslint/js": ^9.35.0
  "@stylistic/eslint-plugin": ^5.3.1
  eslint-config-flat-gitignore: ^2.1.0
  eslint-flat-config-utils: ^2.1.1
  eslint-plugin-perfectionist: ^4.15.0
  eslint-plugin-regexp: ^2.10.0
  eslint-plugin-unicorn: ^61.0.2
  globals: ^16.4.0
  "@types/node": ^24.3.3
  tsdown: ^0.15.1
  typescript: ^5.9.2
  eslint-plugin-better-tailwindcss: ^3.7.8
