catalog:
  '@unocss/eslint-config': ^66.4.2
  eslint: ^9.33.0
  eslint-plugin-svelte: ^3.11.0
  typescript-eslint: ^8.40.0
  '@eslint/js': ^9.33.0
  '@stylistic/eslint-plugin': ^5.2.3
  eslint-config-flat-gitignore: ^2.1.0
  eslint-flat-config-utils: ^2.1.1
  eslint-plugin-perfectionist: ^4.15.0
  eslint-plugin-regexp: ^2.10.0
  eslint-plugin-unicorn: ^60.0.0
  globals: ^16.3.0
  '@types/node': ^24.3.0
  tsdown: ^0.14.1
  typescript: ^5.9.2
