catalog:
  '@unocss/eslint-plugin': ^66.5.11
  eslint: ^9.39.2
  eslint-plugin-svelte: ^3.13.1
  typescript-eslint: ^8.50.1
  '@eslint/js': ^9.39.2
  '@stylistic/eslint-plugin': ^5.6.1
  eslint-config-flat-gitignore: ^2.1.0
  eslint-flat-config-utils: ^2.1.4
  eslint-plugin-perfectionist: ^4.15.1
  eslint-plugin-regexp: ^2.10.0
  eslint-plugin-unicorn: ^61.0.2
  globals: ^16.5.0
  '@types/node': ^25.0.3
  tsdown: ^0.18.3
  typescript: ^5.9.3
  eslint-plugin-better-tailwindcss: ^3.8.0
